# ./docker-compose.yml

version: "3"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: comanda_db
      MYSQL_USER: comanda_user
      MYSQL_PASSWORD: comanda123
    ports:
      - "9907:3306"
  web:
    image: php:7.2.2-apache
    container_name: comanda
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
    ports:
      - "5000:80"
    stdin_open: true
    tty: true
